Two new features: Ignore if existed and exit after no more commands

diff --git a/bq b/bq
--- a/bq
+++ b/bq
@@ -16,13 +16,26 @@
 
 # ----------------------------------------------------------------------
 
-die() { echo "$@" >&2; exit 1; }
+die() {
+  echo "$@" >&2
+  exit 1
+}
+
+ignoreEX=""
+[ "$1" = "-i" ] && {
+  ignoreEX=" -i"
+  shift
+}
 
 [ "$1" = "-h" ] && {
-    cat <<-EOF
+  cat <<-EOF
 	Example usage:
 	    # start a worker
 	    bq -w
+	    # exit if worker could not find any command to run after 60 seconds
+	    bq -e -w
+	    # start only 1 worker, ignore if there is already running, and exit if no new command
+	    bq -i -e -w
 	    # submit a job
 	    bq some-command arg1 arg2 [...]
 	    # check status
@@ -32,7 +45,7 @@ die() { echo "$@" >&2; exit 1; }
 	    # shell meta characters (;, &, &&, ||, >, <, etc), do this:
 	    bq bash -c 'echo hello; echo there >junk.\$RANDOM'
 	EOF
-    exit 1
+  exit 1
 }
 
 # ----------------------------------------------------------------------
@@ -44,8 +57,10 @@ TMP=/dev/shm
 # I doubt I will ever use multiple Qs, but it's easy enough to implement
 Q=default
 [ "$1" = "-q" ] && {
-    [ -z "$2" ] && die "-q needs a queue name"
-    Q=$2; shift; shift
+  [ -z "$2" ] && die "-q needs a queue name"
+  Q=$2
+  shift
+  shift
 }
 [ -z "$QDIR" ] && export QDIR=$TMP/bq-$USER-$Q
 mkdir -p $QDIR/w
@@ -56,41 +71,40 @@ mkdir -p $QDIR/OK
 # WORK 1 TASK
 
 _work_1() {
-    ID=$1
+  ID=$1
 
-    # "claim" the task in q by renaming q/$ID to a name that contains our own PID
-    mv q/$ID $ID.running.$$ 2>/dev/null
+  # "claim" the task in q by renaming q/$ID to a name that contains our own PID
+  mv q/$ID $ID.running.$$ 2>/dev/null
 
-    # if the "claim" succeeded, we won the race to run the task
-    if [ -f $ID.running.$$ ]
-    then
-        # get the command line arguments and run them
-        readarray -t cmd < $ID.running.$$
+  # if the "claim" succeeded, we won the race to run the task
+  if [ -f $ID.running.$$ ]; then
+    # get the command line arguments and run them
+    readarray -t cmd <$ID.running.$$
 
-        # the first line is the directory to be in; shift that out first
-        newpwd="${cmd[0]}"
-        cmd=("${cmd[@]:1}")
+    # the first line is the directory to be in; shift that out first
+    newpwd="${cmd[0]}"
+    cmd=("${cmd[@]:1}")
 
-        # log the command for debugging later
-        echo -n "cd $newpwd; ${cmd[@]}" >> w/$$
+    # log the command for debugging later
+    echo -n "cd $newpwd; ${cmd[@]}" >>w/$$
 
-        # the directory may have disappeared between submitting the
-        # job and running it now.  Catch that by trying to cd to it
-        cd "$newpwd" || cmd=(cd "$newpwd")
-        # if the cd failed, we simply replace the actual command with
-        # the same "cd", and let it run and catch the error.  Bit of a
-        # subterfuge, actually, but it works fine.
+    # the directory may have disappeared between submitting the
+    # job and running it now.  Catch that by trying to cd to it
+    cd "$newpwd" || cmd=(cd "$newpwd")
+    # if the cd failed, we simply replace the actual command with
+    # the same "cd", and let it run and catch the error.  Bit of a
+    # subterfuge, actually, but it works fine.
 
-        # finally we run the task.  Note that our PWD now is NOT $QDIR, so
-        # the two redirected filenames have to be fully qualified
-        "${cmd[@]}" > $QDIR/$ID.1 2> $QDIR/$ID.2
-        ec=$?
+    # finally we run the task.  Note that our PWD now is NOT $QDIR, so
+    # the two redirected filenames have to be fully qualified
+    "${cmd[@]}" >$QDIR/$ID.1 2>$QDIR/$ID.2
+    ec=$?
 
-        cd $QDIR
-        mv $ID.running.$$ $ID.exitcode=$ec
-        [ "$ec" = "0" ] && mv $ID.* OK
-        echo " # $ec" >> w/$$
-    fi
+    cd $QDIR
+    mv $ID.running.$$ $ID.exitcode=$ec
+    [ "$ec" = "0" ] && mv $ID.* OK
+    echo " # $ec" >>w/$$
+  fi
 }
 
 # ----------------------------------------------------------------------
@@ -98,29 +112,44 @@ _work_1() {
 
 # '-w' starts a worker; each worker runs one job at a time, so if you want
 # more jobs to run simultaneously, run this multiple times!
+exitRA=""
+[ "$1" = "-e" ] && [ "$2" = "-w" ] && {
+  exitRA=" -e"
+  shift
+}
+
 [ "$1" = "-w" ] && [ -z "$2" ] && {
+  running=$(
+    cd $QDIR/w
+    ls | grep -v exited | wc -l
+  )
 
-    # if the user is starting a worker, any existing kill commands don't apply
-    rm -f $QDIR/q/0.*.-k
+  [ "$ignoreEX" != "" ] && [ "$running" -gt "1" ] && echo "ignoring since existed" && exit 1
 
-    # daemonize
-    nohup "$0" -w $QDIR &
+  # if the user is starting a worker, any existing kill commands don't apply
+  rm -f $QDIR/q/0.*.-k
 
-    # remind the user how many workers he has started, in case he forgot
-    sleep 0.5   # wait for the other task to kick off
-    echo `cd $QDIR/w; ls | grep -v exited | wc -l` workers running
-    exit 0
+  # daemonize
+  nohup "$0"${exitRA} -w $QDIR &
+
+  # remind the user how many workers he has started, in case he forgot
+  sleep 0.5 # wait for the other task to kick off
+  echo $(
+    cd $QDIR/w
+    ls | grep -v exited | wc -l
+  ) workers running
+  exit 0
 }
 
 # ----------------------------------------------------------------------
 # STOP A WORKER
 
 [ "$1" = "-k" ] && [ -z "$2" ] && {
-    touch $QDIR/q/0.$$.-k
-    # starting with a "0" assures that in an "ls" this file will come before
-    # any normal task files (which all start with `date +%s`).  The contents
-    # don't matter, since it won't be "executed" in the normal manner.
-    exit 0
+  touch $QDIR/q/0.$$.-k
+  # starting with a "0" assures that in an "ls" this file will come before
+  # any normal task files (which all start with `date +%s`).  The contents
+  # don't matter, since it won't be "executed" in the normal manner.
+  exit 0
 }
 
 # ----------------------------------------------------------------------
@@ -128,42 +157,50 @@ _work_1() {
 
 [ "$1" = "-w" ] && {
 
-    touch $QDIR/w/$$
+  touch $QDIR/w/$$
 
-    while :
-    do
-        cd $QDIR
+  while :; do
+    cd $QDIR
 
-        ID=`cd q; ls | head -1`
-        # if nothing is waiting in q, go to sleep, but use inotifywait so you
-        # get woken up immediately if a new task lands
-        [ -z "$ID" ] && {
-            inotifywait -q -t 60 -e create q >/dev/null
-            continue
-            # whether we got an event or just timed out, we just go back round
-        }
+    ID=$(
+      cd q
+      ls | head -1
+    )
+    # if nothing is waiting in q, go to sleep, but use inotifywait so you
+    # get woken up immediately if a new task lands
+    [ -z "$ID" ] && {
+      inotifywait -q -t 60 -e create q >/dev/null
+      # Exit if waited for 60 seconds
+      [ "${exitRA}" != "" ] && {
+        pwd >&2
+        "$0" -k
+        exit 0
+      }
+      continue
+      # whether we got an event or just timed out, we just go back round
+    }
 
-        # note there is still a bit of a race here.  If tasks were submitted
-        # *between* the "ID=" and the "inotifywait" above, they will end up
-        # waiting 60 seconds before they get picked up.  Hopefully that's a
-        # corner case, and anyway at worst it only causes a delay.
+    # note there is still a bit of a race here.  If tasks were submitted
+    # *between* the "ID=" and the "inotifywait" above, they will end up
+    # waiting 60 seconds before they get picked up.  Hopefully that's a
+    # corner case, and anyway at worst it only causes a delay.
 
-        # handle exit, again using the "mv is atomic" principle
-        [[ $ID == 0.*.-k ]] && {
-            mv q/$ID $ID.exiting
-            [ -f     $ID.exiting ] && {
-                mv w/$$ w/$$.exited
-                rm $ID.exiting
-                exit 0
-            }
-        }
+    # handle exit, again using the "mv is atomic" principle
+    [[ $ID == 0.*.-k ]] && {
+      mv q/$ID $ID.exiting
+      [ -f $ID.exiting ] && {
+        mv w/$$ w/$$.exited
+        rm $ID.exiting
+        exit 0
+      }
+    }
 
-        # ok there was at least one task waiting; try to "work" it
-        _work_1 $ID
-    done
+    # ok there was at least one task waiting; try to "work" it
+    _work_1 $ID
+  done
 
-    # we should never get here
-    touch $QDIR/worker.$$.unexpected-error
+  # we should never get here
+  touch $QDIR/worker.$$.unexpected-error
 }
 
 # ----------------------------------------------------------------------
@@ -175,9 +212,9 @@ _work_1() {
 # ----------------------------------------------------------------------
 
 # some command was given; add it to the queue
-ID=`date +%s`.$$.${1//[^a-z0-9_.-]/}
-pwd                 > $QDIR/q/$ID
-printf "%s\n" "$@" >> $QDIR/q/$ID
+ID=$(date +%s).$$.${1//[^a-z0-9_.-]/}
+pwd >$QDIR/q/$ID
+printf "%s\n" "$@" >>$QDIR/q/$ID
 
 # Print the ID for tracking
 echo "Queued job with id:" >&2
